/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ApartamentoIdRouteImport } from './routes/apartamento.$id'
import { Route as PerfilAgentesRouteImport } from './routes/perfil.agentes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentoIdRoute = ApartamentoIdRouteImport.update({
  id: '/apartamento/$id',
  path: '/apartamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilAgentesRoute = PerfilAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => PerfilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/apartamento/$id': typeof ApartamentoIdRoute
  '/perfil/agentes': typeof PerfilAgentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/apartamento/$id': typeof ApartamentoIdRoute
  '/perfil/agentes': typeof PerfilAgentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/apartamento/$id': typeof ApartamentoIdRoute
  '/perfil/agentes': typeof PerfilAgentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anunciar'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/favoritos'
    | '/mensagens'
    | '/perfil'
    | '/apartamento/$id'
    | '/perfil/agentes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anunciar'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/favoritos'
    | '/mensagens'
    | '/perfil'
    | '/apartamento/$id'
    | '/perfil/agentes'
  id:
    | '__root__'
    | '/'
    | '/anunciar'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/favoritos'
    | '/mensagens'
    | '/perfil'
    | '/apartamento/$id'
    | '/perfil/agentes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciarRoute: typeof AnunciarRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  FavoritosRoute: typeof FavoritosRoute
  MensagensRoute: typeof MensagensRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  ApartamentoIdRoute: typeof ApartamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamento/$id': {
      id: '/apartamento/$id'
      path: '/apartamento/$id'
      fullPath: '/apartamento/$id'
      preLoaderRoute: typeof ApartamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/agentes': {
      id: '/perfil/agentes'
      path: '/agentes'
      fullPath: '/perfil/agentes'
      preLoaderRoute: typeof PerfilAgentesRouteImport
      parentRoute: typeof PerfilRoute
    }
  }
}

interface PerfilRouteChildren {
  PerfilAgentesRoute: typeof PerfilAgentesRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilAgentesRoute: PerfilAgentesRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciarRoute: AnunciarRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  FavoritosRoute: FavoritosRoute,
  MensagensRoute: MensagensRoute,
  PerfilRoute: PerfilRouteWithChildren,
  ApartamentoIdRoute: ApartamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
